### PR TITLE
Deeper tests using jsx-chai.

### PR DESCRIPTION
**Pull request by rgbkrk**
Started stubbing out some tests here based on @betatim's proposal to use jsx-chai. Pretty slick.

### CODE REVIEW

**Comment by rgbkrk** [comment]
Slick, ready for review.

**Comment by betatim** [comment]
:ship:

**Comment by betatim** [comment]
Did you find a way to express something like `expect(result).to.deep.equal(<ConsoleText * />);` => match a `ConsoleText` component independent of its props.

For `ConsoleText` it is easy to specify the text prop, but for more complicated components it is a bit tedious. I'd like to know if there is a nice pattern for checking this.

For future @betatim: find out why I didn't use

```
import shallowRender from 'react-shallow-render';
// shallow render the component under test
const renderedTree = shallowRender(<Page heading={headingElement} />);
```

which should work for [testing stateless components](https://jamesfriend.com.au/better-assertions-shallow-rendered-react-components) and save us some typing

**Comment by rgbkrk** [comment]
No, I didn't find any glob ways of doing it. Then again, I do want to know the right props passed through.

**Pull request merged**
